### ISSUE TITLE
프로필 상세 화면 구현

### ISSUE THREAD

**Issue by quessr** [LayTheGroundWork/Eighteen_Android#20]
## 💡 Issue

프로필 상세화면 구현

## 📝 todo
- [x] 프로필 이미지 슬라이드 구현
- [x] 이름,학교 섹션 ui 구현
- [x] 자기소개 섹션 ui 구현
- [x] 10문10답 RecyclerView 어댑터 구현
- [x] 10문10답 펼쳐서 보기/ 접기 기능 구현 
- [x] 프로필상세 뷰모델 구현
- [x] scrollview로 구현된 레이아웃 recyclerview로 리팩토링
- [x] header 구현
- [x] footer 구현
- [x] 좋아요 구현
- [x] 스크롤 위치에 따라 헤더색상 변경 기능 구현
- [x] 닫기버튼 클릭시 메인화면으로 이동 기능 추가
- [x] 오버플로 메뉴 클릭시 신고하기/차단하기 다이얼로그 연결 추가
- [x] viewpager2 position 유지 기능 구현
- [x] Recyclerview 스크롤시, header 색상 변경 기능 구현
- [x] viewpager2 동영상 미디어 처리 추가
- [x] 동영상 자동재생 연결 추가
- [x] 볼륨 아이콘 색상변경 및 토글 기능 추가 (white icon을 tint 옵션을 주는 방식으로 변경)
- [x] 자기소개, 자문자답 데이터 없는 경우 처리
