### ISSUE TITLE
회원가입 구현

### ISSUE THREAD

**Issue by kim0hoon** [LayTheGroundWork/Eighteen_Android#37]
## 💡 Issue
회원가입 플로우 구현

## 📝 todo
- [x] 로그인 페이지 구현
- [x] 전화번호 입력 페이지 구현
- [x] 인증코드 입력 구현
- [x] 약관 동의 페이지 구현
- [x] 아이디 입력 페이지 구현
- [x] 닉네임 입력 페이지 구현
- [x] 생년월일 페이지 구현
- [x] 학교 입력 구현
- [x] 태그 입력 페이지 구현
- [x] 미디어 추가 페이지 구현
- [x] 프로필 등록 완료 페이지 및 등록완료 구현
- [x] 이전페이지 이동 시 이벤트 발행으로 변경
- [x] 미디어 추가 2번클릭 시 버그 수정
- [x] 로그인 클릭 이동
- [x] 로딩, 에러처리
- [x] 삭제아이콘 디자인(문의 중)
- [x] 우상단 x버튼
- [x] 약관 url 적용(#100으로 이동)
- [x] 사진선택 가이드 추가
- [x] 사진선택 가이드 내용 추가
- [x] 회원가입 완료페이지 백버튼 제거(+회원가입 api 호출 페이지 앞으로 변경)
- [x] textfield 크기 변경 적용
- [x] 회원가입 response(문의 중)
- [x] id 중복체크
- [x] api 요청 필드 추가 적용
- [x] 대표사진 없이 사진 등록 가능하도록 변경(추가버튼이 계속 늘어남 3개유지)
- [x] 인증 팝업 추가
- [x] SignUpViewModel 뷰모델 테스트 데이터 삭제
