### ISSUE TITLE
메인화면 UI 리팩토링

### ISSUE THREAD

**Issue by yys7517** [LayTheGroundWork/Eighteen_Android#39]
## 💡 Issue

- 메인화면 Infinite Scroll 적용하여 UI 수정

## 📝 todo
- [x] Header 아이템 
- [x] Teen 칩 버튼 아이템
- [x] Teen 프로필 아이템
- [x] Divider 아이템
- [x] About Teen 아이템
- [x] Header + 더보기 아이템
- [x] 토너먼트 아이템
- [x] 메인화면 Adapter + ViewType 
- [x] 더미 데이터
