### ISSUE TITLE
메인화면 리팩토링 phase2

### ISSUE THREAD

**Issue by yys7517** [LayTheGroundWork/Eighteen_Android#55]
## 💡 Issue

메인화면 리팩토링 phase 2

## 📝 todo
- [x] 람다식 제거 
- [x] 메인 어댑터 클릭 이벤트 리스너 사용
- [x] 리스너 인터페이스 
- [x] 신고, 차단 다이얼로그 Anchor View
- [x] 메인화면 탑 버튼
- [x] 스크롤에 따른 메인화면 탑 버튼 visibility 설정
- [x] 신고, 차단 팝업 showReportSelectLeft
- [x] 신고, 차단 팝업 showReportSelectBottom
- [x] 중복 클릭 방지를 위한 Flow Binding 적용
- [x] 메인화면 스크롤 상태 유지
- [x] 카테고리 태그 버튼 크기 조절
- [x] 인기 Teen 유저 아이템 크기 조정
- [x] 인기 Teen 자동 스크롤
