### ISSUE TITLE
뱃지 상세 페이지

### ISSUE THREAD

**Issue by kim0hoon** [LayTheGroundWork/Eighteen_Android#65]
## 💡 Issue
- 뱃지 상세 페이지 구현

## 📝 todo
- [x] 뱃지 상세 페이지 추가
- [x] 뱃지 클릭 다이얼로그 추가
- [x] 뱃지 추가(기획, api 확인 필요) - (#100 으로 이동)
