### ISSUE TITLE
에러 및 로딩 추가

### ISSUE THREAD

**Issue by kim0hoon** [LayTheGroundWork/Eighteen_Android#88]
## 💡 Issue
- 에러 및 로딩 뷰 추가, 적용

## 📝 todo
- [x] 에러 layout 구현
- [x] 로딩 layout 구현
- [x] 에러 메시지 수정(문의 중) - (#100 으로 이동)
